project_id = "taebkngjvmekjdkacvxy"

[functions.analyze-resume]
verify_jwt = false

[functions.analyze-jd]
verify_jwt = false

[functions.generate-question]
verify_jwt = false

[functions.evaluate-answer]
verify_jwt = false
